version: 1.0.{build}
build_script:
- cmd: >-
    appveyor_build.bat
shallow_clone: true
test: off
artifacts:
- path: nginx-bin.7z
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
deploy:
- provider: Environment
  name: github
  on:
    branch: release-1.24.0
    appveyor_repo_tag: true